apiVersion: 1

datasources:
  - name: aiSpeechMulti SQLite
    type: frser-sqlite-datasource
    uid: aiSpeechMulti-sqlite
    access: proxy
    isDefault: true
    jsonData:
      path: /data/aiSpeechMulti.db
    version: 1
    editable: true
